arguments:
  parameters:
  - name: application-name
    value: pipeline14-app1
  - name: application-name-2
    value: pipeline14-app2
  - name: revision
    value: HEAD
  - name: argocd-server-address
    value: 192.168.64.12:31644
  - name: argocd-credentials-secret
    value: argocd-credentials-secret
